// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUO3zpS6fbJxBtPo33Djer2onIkDcWlys',
    appId: '1:745408592212:web:a2f5de41b650e41775f0c1',
    messagingSenderId: '745408592212',
    projectId: 'simulador-detran',
    authDomain: 'simulador-detran.firebaseapp.com',
    storageBucket: 'simulador-detran.appspot.com',
    measurementId: 'G-8YD5VB4K3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjSa6p53u-d2R-9a102xpeg5zOrrkQQ2w',
    appId: '1:745408592212:android:9026221ba7eebb4475f0c1',
    messagingSenderId: '745408592212',
    projectId: 'simulador-detran',
    storageBucket: 'simulador-detran.appspot.com',
  );
}
